name: Pull Request Workflow

on: [ pull_request ]

jobs:
  build:
    runs-on: linux-x64
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'corretto'
          cache: 'gradle'
      - uses: actions/cache@v5
        with:
          path: "/home/runner/.konan"
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev
      - name: Build with Gradle
        run: ./gradlew buildAllLinuxBinaries
  static-code-analysis:
    name: Static Code Analysis
    runs-on: linux-arm64
    timeout-minutes: 30
    steps:
      - name: Run detekt
        uses: monta-app/detekt-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
