name: Pull Request Workflow

on: [ pull_request ]

jobs:
  build:
    runs-on: linux-x64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: '25'
          distribution: 'corretto'
          cache: 'gradle'
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: "/home/runner/.konan"
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev
      - name: Build with Gradle
        run: ./gradlew buildAllLinuxBinaries
  static-code-analysis:
    name: Static Code Analysis
    runs-on: linux-arm64
    timeout-minutes: 30
    steps:
      - name: Run detekt
        uses: monta-app/detekt-action@edb1cfd83a2e23ceff88f39453b130e7bc18cd7f # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
