name: Pull Request Workflow

on: [ pull_request ]

jobs:
  test:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"
          cache-dependency-path: go.sum
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test -v -race -coverprofile=coverage.out ./...
      - name: Generate coverage report
        run: go tool cover -html=coverage.out -o coverage.html
      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html
      - name: Build application
        run: make build
      - name: Test CLI help
        run: ./bin/slack-notifier-cli --help
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.4"
          cache-dependency-path: go.sum
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m
