name: Test

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: linux-x64
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: '25'
          distribution: 'corretto'
          cache: 'gradle'
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: "/home/runner/.konan"
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install libcurl4-openssl-dev
      - name: Build x64 and ARM64 binaries
        run: ./gradlew buildAllLinuxBinaries
      - name: Prepare binaries
        run: |
          cp build/bin/host/releaseExecutable/slack-notifier-cli.kexe ./slack-notifier-cli-X64
          cp build/bin/linuxArm64/releaseExecutable/slack-notifier-cli.kexe ./slack-notifier-cli-ARM64
          chmod +x ./slack-notifier-cli-X64 ./slack-notifier-cli-ARM64
      - name: Upload x64 executable
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: slack-notifier-cli-X64
          path: slack-notifier-cli-X64
      - name: Upload ARM64 executable
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: slack-notifier-cli-ARM64
          path: slack-notifier-cli-ARM64
